index.js, src/generate-common-seo.js, test/generate_common_seo_test.js
Following keys needs to be added to db within `theme_attributes`
```json
{
"twitter_app_name_ipad": "",
"twitter_app_name_googleplay": "",
"twitter_app_id_googleplay": "",
"twitter_app_name_iphone": "",
"twitter_app_id_iphone": "",
"apple_itunes_app": "",
"google_play_app": "",
"fb_app_id": "",
"fb_pages": "",
"logo": ""
}
```
=> SEO Refactoring

src/structured-data-tags.js
`ld+json` - article / newsarticle should only be available on story pages.
=> Implement `ld+json` only on story pages

src/text-tags.js, test/text_tags_test.js
Section Seo-metadata fallback
- page-title to section-name
- title to section-name
- description to home seo description
=> Section Seo-Metadata fallback

src/image-tags.js, test/image_tags_test.js
**Description**
- Pass element id along with story card id as query param
- As of now element id is used to pick image url from element
=> bloombergquint-node#issue-272 implemented element share

package-lock.json, package.json, src/generate-common-seo.js, src/structured-data/structured-data-tags.js, test/generate_common_seo_test.js
Closes issue: [https://github.com/quintype/madrid/issues/422](url)
=> Implement type ImageObject for logo, bump minor version

package-lock.json, package.json, src/image-tags.js, src/text-tags.js, test/text_tags_test.js
Headline will be picked up as `twitter:title` for story pages and metadata will be used for the other pages
=> Pick twitter title as headline for story

src/structured-data/structured-data-tags.js, test/structured_data_tags_test.js
Remove HTML tags from articleBody text
Put stripping HTML from article body behind a toggle
=> Put stripping HTML from `ArticleBody` behind a toggle

src/image-tags.js, src/text-tags.js, test/image_tags_test.js
https://github.com/quintype/ace-support/issues/568
=> feat(configure social alternatives)

src/structured-data/structured-data-tags.js, test/structured_data_tags_test.js
@sharangj Can you please review this change and let us know if it can be merged with the master.
=> Added custom page support

package-lock.json, package.json, src/amp-tags.js, test/amp_tags_test.js
fix for https://github.com/quintype/madrid/issues/2841
=> fix(amp): Amp is not working on subdirectory

src/amp-tags.js, test/amp_tags_test.js
https://github.com/quintype/ace-planning/issues/14
=> fix(support  decoded amp URLs for amp): Commit

src/image-tags.js, test/image_tags_test.js
https://github.com/quintype/prothomalo-bugs/issues/354
=> Fix(imageTag) : added `fm = webp`  to imageTag

src/image-tags.js, test/image_tags_test.js
Reverts quintype/quintype-node-seo#283
=> Revert "Fix(imageTag) : added `fm = webp`  to imageTag"

src/structured-data/structured-data-tags.js, test/structured_data_tags_test.js
fix: author, date modified, headline and description errors
Structure data testing tool
=> fix: errors in live blog posting structure data

package-lock.json, package.json
Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.
=> fix: update package to 1.38.30

package-lock.json, package.json
Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.
=> revert gh-pages

.circleci/config.yml
Builds on circle ci were failing. This was because of old node version in circle ci config.
=> fix: update node version in circle ci config

package-lock.json, package.json, src/image-tags.js
Cannot destructure property 'image' of 'pickImage(...)' as it is undefined
Fixes # https://github.com/quintype/ace-planning/issues/489
=> Fix(pickImage): image is undefined of pickImage

package-lock.json, package.json, src/text-tags.js
Fixes - https://github.com/quintype/quintype-node-framework/pull/307
=> feat(SEO) : Support SEO Metadata in static pages

package-lock.json, package.json, src/image-tags.js, test/image_tags_test.js
Fixes - https://github.com/quintype/page-builder/issues/1923
=> fix(og-image) : Support enlarge=true param in og image

package-lock.json, package.json, src/structured-data/structured-data-tags.js
fixes 
Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.
=> fix(embed-url): use fallback when story elements are not there

index.js
Fixed : Added **itemprop** in the standard html tag list
ISSUE :
**https://github.com/quintype/ace-planning/issues/622**
=> Add ItemProp in the standart html tag list

package-lock.json, package.json, src/text-tags.js
closes https://github.com/quintype/page-builder/issues/2109
=> feat(canonical): Add canonical url toggle

src/author-tags.js, src/generate-common-seo.js, test/author_tags_test.js, test/generate_common_seo_test.js
https://github.com/quintype/page-builder/issues/2072
=> feat(twitter): Implement additional twitter tags

package-lock.json, package.json, src/author-tags.js, src/generate-common-seo.js
Hotfix for https://github.com/quintype/page-builder/issues/2134
=> bugfix: twitterUrl cannot read property of null

package-lock.json, package.json, src/text-tags.js
Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.
=> Peer deps removal

package-lock.json, package.json, src/image-tags.js, src/structured-data/structured-data-tags.js, src/utils.js, test/image_tags_test.js, test/structured_data_tags_test.js
Generate social share watermark for stories
Feature:
Bold now supports adding an image watermarking
Added watermark on story hero image - on social sharing
https://github.com/quintype/ace-planning/issues/754
=> Watermark for HeroImage on Social Sharing

package-lock.json, package.json, src/utils.js
Ref ticket: https://github.com/quintype/ace-planning/issues/853
Added fallback as false if water mark is not available.
=> fix: Add fallback for watermark image

package-lock.json, package.json, src/amp-tags.js
Reference: https://github.com/quintype/page-builder/issues/2737
=> feat: add support to configure amp story page

index.js, package-lock.json, package.json, src/structured-data/schema.js, src/structured-data/structured-data-tags.js
Ticket: https://github.com/quintype/page-builder/issues/2957
=> Added Author Schema for Schema Validation 

package-lock.json, package.json, src/structured-data/structured-data-tags.js
Ticket: https://github.com/quintype/page-builder/issues/3258
=> Liveblog Schema Update for card content

package-lock.json, package.json, src/structured-data/structured-data-tags.js
https://github.com/quintype/page-builder/issues/3054
https://github.com/quintype/page-builder/issues/3521
=> feat(sponsor schema): update article and news article schema for sponsored stories

package-lock.json, package.json, src/structured-data/structured-data-tags.js, src/utils.js
Ticket: https://github.com/quintype/page-builder/issues/3267
=> feat(media-gallery): add media gallery schema to visual stories

package-lock.json, package.json, src/structured-data/structured-data-tags.js, src/utils.js
https://github.com/quintype/page-builder/issues/3267
=> fix(schema): fix media gallery schema

package-lock.json, package.json, src/structured-data/structured-data-tags.js
fix: https://github.com/quintype/page-builder/issues/3807
=> feat: add event schema support when eventDetails exist in story data
